# Generated by Django 2.2.3 on 2019-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('rescomp', models.TextField(blank=True, null=True)),
                ('resrun', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
